version: '3.8'

services:
  workers:
    image: workers:latest
    container_name: workers_editor
    build: .
    restart: always
    ports:
      - "21111:21111"  # [修改点] 外部:内部
    volumes:
      - ./data:/app/data
    environment:
      - PORT=21111     # [修改点] 内部端口
      - TZ=Asia/Shanghai